management:
  context-path: /manage
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fra
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: create