management:
  context-path: /manage
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fra
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
