management:
  context-path: /manage
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fra
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
  thymeleaf:
      cache: false